### ISSUE TITLE
Error fails

### ISSUE THREAD

**Issue by lucarin91** [di-unipi-socc/TosKer#34]
Somotimes the test `Test_Node_Mongo_Mix2` fails with the error:
```
FAIL: test (tests.test_tosca_node_mongo_mix2.Test_Node_Mongo_Mix2)
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/home/travis/build/di-unipi-socc/TosKer/tests/test_tosca_node_mongo_mix2.py", line 13, in test
 self.create()
 File "/home/travis/build/di-unipi-socc/TosKer/tests/test_tosca_base.py", line 33, in create
 docker.inspect_container(c)
AssertionError: unexpectedly None
```

**Comment by lucarin91** [comment]
Probably this was a Trevis problem with Docker images
